name: meson_test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-with-clang:
    runs-on: ubuntu-22.04

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update &&
          sudo apt-get install \
            libwayland-dev meson

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build & Test
        run: |
          meson build
          ninja -C build test

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: zen-protocols-test-log
          path: build/meson-logs/
